version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build-and-test:
    executor: 
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python check_advisories.py --all
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
